namespace BizFirst.Integration.Ethereum.Services;

using Nethereum.JsonRpc.Client;
using Nethereum.Util;

/// <summary>
/// ENS (Ethereum Name Service) resource: forward/reverse resolution, text records, and resolver
/// lookup. All 5 operations are read-only — no signing required.
///
/// This is a MANUAL implementation of the ENS resolution algorithm (namehash + classic
/// Registry→Resolver two-step lookup) rather than a dependency on the dedicated Nethereum.ENS /
/// Nethereum.ENS.ENSRegistry NuGet packages, which are not currently referenced by this project
/// (only Nethereum.Web3 6.0.0 is). See the "// VERIFY:" comments below for the specific points that
/// should be double-checked (or that justify adding the dedicated package) before this is relied on
/// beyond plain-ASCII ".eth" names on Ethereum mainnet.
///
/// The namehash algorithm (<see cref="ComputeNamehash"/>), the Registry/Resolver ABI function
/// selectors, and the byte[]-as-bytes32 ABI encoding this relies on were all independently verified
/// while building this service: the namehash of "eth" was cross-checked against both a standalone
/// pycryptodome keccak256 implementation and the published EIP-137 example test vector
/// (0x93cdeb708b7545dc668eb9280176169d1c33cfd8ed6f04690a0bcc88a93fc4ae), and the four function
/// selectors generated by Nethereum's ABI encoder for resolver(bytes32)/addr(bytes32)/name(bytes32)/
/// text(bytes32,string) — 0x0178b8bf / 0x3b3b57de / 0x691f3431 / 0x59d1d43c respectively — all match
/// the well-known ENS Registry/Public Resolver selectors.
/// </summary>
public sealed class EthereumEnsService
{
    /// <summary>
    /// Classic ENS Registry contract. Deployed via a deterministic deployment proxy at this same
    /// address on Ethereum mainnet plus several historical testnets (Ropsten/Rinkeby/Goerli/Sepolia).
    /// </summary>
    private const string EnsRegistryAddress = "0x314159265dD8dbb310642f98f50C066173C1259";

    private const string RegistryAbi = @"[
      {""constant"":true,""inputs"":[{""name"":""node"",""type"":""bytes32""}],""name"":""resolver"",""outputs"":[{""name"":"""",""type"":""address""}],""type"":""function""}
    ]";

    /// <summary>Minimal ENS Public Resolver interface: the 3 read functions this resource calls.</summary>
    private const string ResolverAbi = @"[
      {""constant"":true,""inputs"":[{""name"":""node"",""type"":""bytes32""}],""name"":""addr"",""outputs"":[{""name"":"""",""type"":""address""}],""type"":""function""},
      {""constant"":true,""inputs"":[{""name"":""node"",""type"":""bytes32""}],""name"":""name"",""outputs"":[{""name"":"""",""type"":""string""}],""type"":""function""},
      {""constant"":true,""inputs"":[{""name"":""node"",""type"":""bytes32""},{""name"":""key"",""type"":""string""}],""name"":""text"",""outputs"":[{""name"":"""",""type"":""string""}],""type"":""function""}
    ]";

    private const string ZeroAddress = "0x0000000000000000000000000000000000000000";

    private readonly EthereumConnectionProvider _connectionProvider;
    private readonly ILogger<EthereumEnsService> _logger;

    public EthereumEnsService(EthereumConnectionProvider connectionProvider, ILogger<EthereumEnsService> logger)
    {
        _connectionProvider = connectionProvider ?? throw new ArgumentNullException(nameof(connectionProvider));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>ENS01 — ens/resolve. Forward resolution: ENS name → address.</summary>
    public async Task<EthereumEnsResolveResult> ResolveAsync(
        string? network, string name, CancellationToken cancellationToken = default)
    {
        try
        {
            var web3 = await _connectionProvider.GetReadOnlyClientAsync(network, cancellationToken).ConfigureAwait(false);
            var node = ComputeNamehash(NormalizeName(name));

            var resolverAddress = await GetResolverAddressAsync(web3, node).ConfigureAwait(false);
            if (IsZeroAddress(resolverAddress))
                return EthereumEnsResolveResult.Fail("ENS_NOT_REGISTERED", $"No resolver is set for '{name}' — the name is not registered, or has no resolver configured.");

            var resolver = web3.Eth.GetContract(ResolverAbi, resolverAddress);
            var address = await resolver.GetFunction("addr").CallAsync<string>(node).ConfigureAwait(false);
            if (IsZeroAddress(address))
                return EthereumEnsResolveResult.Fail("ENS_NO_ADDRESS_RECORD", $"'{name}' has a resolver but no address record is set.");

            return EthereumEnsResolveResult.Ok(address, resolverAddress);
        }
        catch (OperationCanceledException) { throw; }
        catch (EthereumNetworkNotConfiguredException ex)
        {
            return EthereumEnsResolveResult.Fail("NETWORK_NOT_CONFIGURED", ex.Message);
        }
        catch (RpcResponseException ex)
        {
            _logger.LogError(ex, "ens/resolve RPC error for {Name} on {Network}", name, network);
            return EthereumEnsResolveResult.Fail("RPC_ERROR", ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ens/resolve unexpected error for {Name} on {Network}", name, network);
            return EthereumEnsResolveResult.Fail("UNEXPECTED_ERROR", ex.Message);
        }
    }

    /// <summary>
    /// ENS02 — ens/reverse. Reverse resolution via the ENS Reverse Registrar convention: namehash of
    /// "{address-without-0x-lowercase}.addr.reverse", then Registry→Resolver→name(bytes32).
    /// </summary>
    public async Task<EthereumEnsReverseResult> ReverseAsync(
        string? network, string address, CancellationToken cancellationToken = default)
    {
        try
        {
            var web3 = await _connectionProvider.GetReadOnlyClientAsync(network, cancellationToken).ConfigureAwait(false);
            var reverseName = $"{NormalizeAddressForReverseNode(address)}.addr.reverse";
            var node = ComputeNamehash(reverseName);

            var resolverAddress = await GetResolverAddressAsync(web3, node).ConfigureAwait(false);
            if (IsZeroAddress(resolverAddress))
                return EthereumEnsReverseResult.Fail("ENS_NOT_REGISTERED", $"No reverse resolver is set for '{address}'.");

            var resolver = web3.Eth.GetContract(ResolverAbi, resolverAddress);
            var name = await resolver.GetFunction("name").CallAsync<string>(node).ConfigureAwait(false);
            if (string.IsNullOrWhiteSpace(name))
                return EthereumEnsReverseResult.Fail("ENS_NO_REVERSE_RECORD", $"'{address}' has a reverse resolver but no name record is set.");

            return EthereumEnsReverseResult.Ok(name, resolverAddress);
        }
        catch (OperationCanceledException) { throw; }
        catch (EthereumNetworkNotConfiguredException ex)
        {
            return EthereumEnsReverseResult.Fail("NETWORK_NOT_CONFIGURED", ex.Message);
        }
        catch (RpcResponseException ex)
        {
            _logger.LogError(ex, "ens/reverse RPC error for {Address} on {Network}", address, network);
            return EthereumEnsReverseResult.Fail("RPC_ERROR", ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ens/reverse unexpected error for {Address} on {Network}", address, network);
            return EthereumEnsReverseResult.Fail("UNEXPECTED_ERROR", ex.Message);
        }
    }

    /// <summary>ENS03 — ens/avatar. Shorthand for the "avatar" text record (ENSIP-12).</summary>
    public async Task<EthereumEnsAvatarResult> GetAvatarAsync(
        string? network, string name, CancellationToken cancellationToken = default)
    {
        try
        {
            var web3 = await _connectionProvider.GetReadOnlyClientAsync(network, cancellationToken).ConfigureAwait(false);
            var (success, _, value, errorCode, errorMessage) =
                await ResolveTextRecordAsync(web3, name, "avatar", cancellationToken).ConfigureAwait(false);

            return success
                ? EthereumEnsAvatarResult.Ok(value)
                : EthereumEnsAvatarResult.Fail(errorCode, errorMessage);
        }
        catch (OperationCanceledException) { throw; }
        catch (EthereumNetworkNotConfiguredException ex)
        {
            return EthereumEnsAvatarResult.Fail("NETWORK_NOT_CONFIGURED", ex.Message);
        }
        catch (RpcResponseException ex)
        {
            _logger.LogError(ex, "ens/avatar RPC error for {Name} on {Network}", name, network);
            return EthereumEnsAvatarResult.Fail("RPC_ERROR", ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ens/avatar unexpected error for {Name} on {Network}", name, network);
            return EthereumEnsAvatarResult.Fail("UNEXPECTED_ERROR", ex.Message);
        }
    }

    /// <summary>ENS04 — ens/text (EIP-634 / ENSIP-5 text records, e.g. "email", "url", "com.twitter").</summary>
    public async Task<EthereumEnsTextResult> GetTextAsync(
        string? network, string name, string key, CancellationToken cancellationToken = default)
    {
        try
        {
            var web3 = await _connectionProvider.GetReadOnlyClientAsync(network, cancellationToken).ConfigureAwait(false);
            var (success, _, value, errorCode, errorMessage) =
                await ResolveTextRecordAsync(web3, name, key, cancellationToken).ConfigureAwait(false);

            return success
                ? EthereumEnsTextResult.Ok(key, value)
                : EthereumEnsTextResult.Fail(errorCode, errorMessage);
        }
        catch (OperationCanceledException) { throw; }
        catch (EthereumNetworkNotConfiguredException ex)
        {
            return EthereumEnsTextResult.Fail("NETWORK_NOT_CONFIGURED", ex.Message);
        }
        catch (RpcResponseException ex)
        {
            _logger.LogError(ex, "ens/text RPC error for {Name}/{Key} on {Network}", name, key, network);
            return EthereumEnsTextResult.Fail("RPC_ERROR", ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ens/text unexpected error for {Name}/{Key} on {Network}", name, key, network);
            return EthereumEnsTextResult.Fail("UNEXPECTED_ERROR", ex.Message);
        }
    }

    /// <summary>
    /// ENS05 — ens/resolver. Registry→resolver(bytes32) only — does not query the resolver contract
    /// itself. Simplest of the 5 operations; useful for debugging resolution failures.
    /// </summary>
    public async Task<EthereumEnsResolverResult> GetResolverAsync(
        string? network, string name, CancellationToken cancellationToken = default)
    {
        try
        {
            var web3 = await _connectionProvider.GetReadOnlyClientAsync(network, cancellationToken).ConfigureAwait(false);
            var node = ComputeNamehash(NormalizeName(name));

            var resolverAddress = await GetResolverAddressAsync(web3, node).ConfigureAwait(false);
            if (IsZeroAddress(resolverAddress))
                return EthereumEnsResolverResult.Fail("ENS_NOT_REGISTERED", $"No resolver is set for '{name}' — the name is not registered, or has no resolver configured.");

            return EthereumEnsResolverResult.Ok(resolverAddress);
        }
        catch (OperationCanceledException) { throw; }
        catch (EthereumNetworkNotConfiguredException ex)
        {
            return EthereumEnsResolverResult.Fail("NETWORK_NOT_CONFIGURED", ex.Message);
        }
        catch (RpcResponseException ex)
        {
            _logger.LogError(ex, "ens/resolver RPC error for {Name} on {Network}", name, network);
            return EthereumEnsResolverResult.Fail("RPC_ERROR", ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ens/resolver unexpected error for {Name} on {Network}", name, network);
            return EthereumEnsResolverResult.Fail("UNEXPECTED_ERROR", ex.Message);
        }
    }

    /// <summary>
    /// Shared Registry→Resolver→text(bytes32,string) lookup used by both <see cref="GetAvatarAsync"/>
    /// and <see cref="GetTextAsync"/>. An empty resolved value with Success=true is normal ENS
    /// behaviour (key simply isn't set) and is NOT treated as a failure — only a missing resolver is.
    /// </summary>
    private static async Task<(bool Success, string ResolverAddress, string Value, string ErrorCode, string ErrorMessage)> ResolveTextRecordAsync(
        IWeb3 web3, string name, string key, CancellationToken cancellationToken)
    {
        var node = ComputeNamehash(NormalizeName(name));

        var resolverAddress = await GetResolverAddressAsync(web3, node).ConfigureAwait(false);
        if (IsZeroAddress(resolverAddress))
            return (false, string.Empty, string.Empty, "ENS_NOT_REGISTERED", $"No resolver is set for '{name}' — the name is not registered, or has no resolver configured.");

        var resolver = web3.Eth.GetContract(ResolverAbi, resolverAddress);
        var value = await resolver.GetFunction("text").CallAsync<string>(node, key).ConfigureAwait(false);
        return (true, resolverAddress, value ?? string.Empty, string.Empty, string.Empty);
    }

    /// <summary>Classic ENS Registry lookup: resolver(bytes32 node) → resolver contract address (zero address if unset).</summary>
    private static async Task<string> GetResolverAddressAsync(IWeb3 web3, byte[] node)
    {
        var registry = web3.Eth.GetContract(RegistryAbi, EnsRegistryAddress);
        return await registry.GetFunction("resolver").CallAsync<string>(node).ConfigureAwait(false);
    }

    /// <summary>
    /// Computes the ENS namehash (EIP-137) for a dot-separated name, e.g. "vitalik.eth". Recursively
    /// hashes labels right-to-left — node = keccak256(parentNode + keccak256(label)), starting from
    /// the all-zero node — using Nethereum's <see cref="Sha3Keccack"/> (keccak256, NOT NIST SHA3).
    ///
    /// // VERIFY: this hashes each label's raw UTF-8 bytes directly and does not apply full ENSIP-15 /
    /// UTS-46 name normalization (case-folding beyond simple ToLowerInvariant, punycode conversion for
    /// non-ASCII labels, confusable-character mapping, emoji handling). For plain-ASCII ".eth" names
    /// this produces the same namehash as official ENS clients (verified during implementation — see
    /// class-level remarks) but names containing non-ASCII characters may compute a different, WRONG
    /// namehash than official resolvers use. Add the dedicated Nethereum.ENS package (which ships a
    /// spec-compliant normalizer) before accepting non-ASCII names from untrusted input.
    /// </summary>
    private static byte[] ComputeNamehash(string name)
    {
        var node = new byte[32];
        if (string.IsNullOrEmpty(name))
            return node;

        var labels = name.Split('.');
        for (var i = labels.Length - 1; i >= 0; i--)
        {
            var labelHash = Sha3Keccack.Current.CalculateHashAsBytes(labels[i]);
            var combined = new byte[64];
            Array.Copy(node, 0, combined, 0, 32);
            Array.Copy(labelHash, 0, combined, 32, 32);
            node = Sha3Keccack.Current.CalculateHash(combined);
        }
        return node;
    }

    /// <summary>ASCII-lowercases and trims a name before hashing. See the // VERIFY: note on <see cref="ComputeNamehash"/>.</summary>
    private static string NormalizeName(string name) => name.Trim().ToLowerInvariant();

    /// <summary>Strips the "0x" prefix and lowercases an address for use as the label in "{addr}.addr.reverse".</summary>
    private static string NormalizeAddressForReverseNode(string address)
    {
        var trimmed = address.Trim();
        if (trimmed.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
            trimmed = trimmed[2..];
        return trimmed.ToLowerInvariant();
    }

    private static bool IsZeroAddress(string? address) =>
        string.IsNullOrWhiteSpace(address) || address.Equals(ZeroAddress, StringComparison.OrdinalIgnoreCase);
}
